/* Generated by scripts/generate_b1_profiles.py; edit config JSON. */
#pragma once
#if defined(CONFIG_B1_DEPLOYMENT_MODE)
#define B1_POLICY_VERSION "deployment-f6888d9c8371a2b2"
#define B1_PROFILE_NAME "deployment"
static void configure_profile(b1_policy_t *p) {
    static const float stable[] = {1200.0f, 2400.0f};
    static const float active[] = {600.0f, 300.0f};
    static const float alert[] = {300.0f, 120.0f, 60.0f};
    const sensor_trust_config_t temperature = {-40.0f, 85.0f, 0.01f, 20, 3.0f, 24, 0.01f, 3};
    sensor_trust_init(&p->temperature, &temperature);
    const sensor_trust_config_t humidity = {0.0f, 100.0f, 0.1f, 20, 10.0f, 24, 0.1f, 3};
    sensor_trust_init(&p->humidity, &humidity);
    p->cd_config.channels[0] = (cd_channel_cfg_t){true, 0.15f};
    p->as_config.delta_channel_use[0] = true;
    p->as_config.delta_noise_floor[0] = 0.15f;
    p->cd_config.channels[1] = (cd_channel_cfg_t){true, 0.8f};
    p->as_config.delta_channel_use[1] = true;
    p->as_config.delta_noise_floor[1] = 0.8f;
    p->cd_config.channels[2] = (cd_channel_cfg_t){false, 1.0f};
    p->as_config.delta_channel_use[2] = false;
    p->as_config.delta_noise_floor[2] = 1.0f;
    p->cd_config.channels[3] = (cd_channel_cfg_t){false, 100.0f};
    p->as_config.delta_channel_use[3] = false;
    p->as_config.delta_noise_floor[3] = 100.0f;
    p->cd_config.variety_window_s = 3600.0f;
    p->cd_config.roc_window_s = 1200.0f;
    p->cd_config.baseline_tau_s = 7200.0f;
    p->cd_config.min_interval_s = 60.0f;
    p->cd_config.event_threshold = 6.0f;
    p->cd_config.event_min_duration_s = 120.0f;
    p->as_config.min_interval = 60.0f;
    p->as_config.default_interval = 1200.0f;
    p->as_config.max_interval = 2400.0f;
    p->as_config.stable_threshold = 2.0f;
    p->as_config.active_threshold = 6.0f;
    p->as_config.hysteresis_fraction = 0.2f;
    p->as_config.ladders[AS_STABLE] = stable;
    p->as_config.ladder_len[AS_STABLE] = sizeof(stable) / sizeof(stable[0]);
    p->as_config.ladder_confirm[AS_STABLE] = 3;
    p->as_config.ladders[AS_ACTIVE] = active;
    p->as_config.ladder_len[AS_ACTIVE] = sizeof(active) / sizeof(active[0]);
    p->as_config.ladder_confirm[AS_ACTIVE] = 2;
    p->as_config.ladders[AS_ALERT] = alert;
    p->as_config.ladder_len[AS_ALERT] = sizeof(alert) / sizeof(alert[0]);
    p->as_config.ladder_confirm[AS_ALERT] = 1;
    p->as_config.up_first_sample = true;
    p->as_config.up_on_event = true;
    p->as_config.up_on_state_change = true;
    p->as_config.up_on_interval_change = true;
    p->as_config.heartbeat_s = 21600.0f;
    p->as_config.delta_threshold = 2.0f;
    p->fault_interval_s = 1200.0f;
    p->degraded_interval_s = 600.0f;
    p->fault_reminder_s = 21600.0f;
    p->temperature_threshold = 32.0f;
    p->temperature_margin = 0.5f;
}
#elif defined(CONFIG_B1_LAB_MODE)
#define B1_POLICY_VERSION "lab-a6ec5a2a2c744d9e"
#define B1_PROFILE_NAME "lab"
static void configure_profile(b1_policy_t *p) {
    static const float stable[] = {2.0f, 4.0f, 5.0f};
    static const float active[] = {2.0f, 1.0f};
    static const float alert[] = {1.0f};
    const sensor_trust_config_t temperature = {-40.0f, 85.0f, 0.01f, 20, 3.0f, 24, 0.01f, 3};
    sensor_trust_init(&p->temperature, &temperature);
    const sensor_trust_config_t humidity = {0.0f, 100.0f, 0.1f, 20, 10.0f, 24, 0.1f, 3};
    sensor_trust_init(&p->humidity, &humidity);
    p->cd_config.channels[0] = (cd_channel_cfg_t){true, 0.15f};
    p->as_config.delta_channel_use[0] = true;
    p->as_config.delta_noise_floor[0] = 0.15f;
    p->cd_config.channels[1] = (cd_channel_cfg_t){true, 0.8f};
    p->as_config.delta_channel_use[1] = true;
    p->as_config.delta_noise_floor[1] = 0.8f;
    p->cd_config.channels[2] = (cd_channel_cfg_t){false, 1.0f};
    p->as_config.delta_channel_use[2] = false;
    p->as_config.delta_noise_floor[2] = 1.0f;
    p->cd_config.channels[3] = (cd_channel_cfg_t){false, 100.0f};
    p->as_config.delta_channel_use[3] = false;
    p->as_config.delta_noise_floor[3] = 100.0f;
    p->cd_config.variety_window_s = 15.0f;
    p->cd_config.roc_window_s = 6.0f;
    p->cd_config.baseline_tau_s = 20.0f;
    p->cd_config.min_interval_s = 1.0f;
    p->cd_config.event_threshold = 6.0f;
    p->cd_config.event_min_duration_s = 4.0f;
    p->as_config.min_interval = 1.0f;
    p->as_config.default_interval = 2.0f;
    p->as_config.max_interval = 5.0f;
    p->as_config.stable_threshold = 2.0f;
    p->as_config.active_threshold = 6.0f;
    p->as_config.hysteresis_fraction = 0.2f;
    p->as_config.ladders[AS_STABLE] = stable;
    p->as_config.ladder_len[AS_STABLE] = sizeof(stable) / sizeof(stable[0]);
    p->as_config.ladder_confirm[AS_STABLE] = 3;
    p->as_config.ladders[AS_ACTIVE] = active;
    p->as_config.ladder_len[AS_ACTIVE] = sizeof(active) / sizeof(active[0]);
    p->as_config.ladder_confirm[AS_ACTIVE] = 2;
    p->as_config.ladders[AS_ALERT] = alert;
    p->as_config.ladder_len[AS_ALERT] = sizeof(alert) / sizeof(alert[0]);
    p->as_config.ladder_confirm[AS_ALERT] = 1;
    p->as_config.up_first_sample = true;
    p->as_config.up_on_event = true;
    p->as_config.up_on_state_change = true;
    p->as_config.up_on_interval_change = true;
    p->as_config.heartbeat_s = 300.0f;
    p->as_config.delta_threshold = 2.0f;
    p->fault_interval_s = 5.0f;
    p->degraded_interval_s = 2.0f;
    p->fault_reminder_s = 300.0f;
    p->temperature_threshold = 32.0f;
    p->temperature_margin = 0.0f;
}
#elif defined(CONFIG_B1_SIMULATION_MODE)
#define B1_POLICY_VERSION "simulation-4dee92778a0ac936"
#define B1_PROFILE_NAME "simulation"
static void configure_profile(b1_policy_t *p) {
    static const float stable[] = {20.0f, 40.0f, 60.0f};
    static const float active[] = {15.0f, 10.0f, 5.0f};
    static const float alert[] = {5.0f};
    const sensor_trust_config_t temperature = {-40.0f, 85.0f, 0.01f, 20, 3.0f, 24, 0.01f, 3};
    sensor_trust_init(&p->temperature, &temperature);
    const sensor_trust_config_t humidity = {0.0f, 100.0f, 0.1f, 20, 10.0f, 24, 0.1f, 3};
    sensor_trust_init(&p->humidity, &humidity);
    p->cd_config.channels[0] = (cd_channel_cfg_t){true, 0.15f};
    p->as_config.delta_channel_use[0] = true;
    p->as_config.delta_noise_floor[0] = 0.15f;
    p->cd_config.channels[1] = (cd_channel_cfg_t){true, 0.8f};
    p->as_config.delta_channel_use[1] = true;
    p->as_config.delta_noise_floor[1] = 0.8f;
    p->cd_config.channels[2] = (cd_channel_cfg_t){false, 1.0f};
    p->as_config.delta_channel_use[2] = false;
    p->as_config.delta_noise_floor[2] = 1.0f;
    p->cd_config.channels[3] = (cd_channel_cfg_t){false, 100.0f};
    p->as_config.delta_channel_use[3] = false;
    p->as_config.delta_noise_floor[3] = 100.0f;
    p->cd_config.variety_window_s = 120.0f;
    p->cd_config.roc_window_s = 40.0f;
    p->cd_config.baseline_tau_s = 120.0f;
    p->cd_config.min_interval_s = 5.0f;
    p->cd_config.event_threshold = 6.0f;
    p->cd_config.event_min_duration_s = 10.0f;
    p->as_config.min_interval = 5.0f;
    p->as_config.default_interval = 20.0f;
    p->as_config.max_interval = 60.0f;
    p->as_config.stable_threshold = 2.0f;
    p->as_config.active_threshold = 6.0f;
    p->as_config.hysteresis_fraction = 0.2f;
    p->as_config.ladders[AS_STABLE] = stable;
    p->as_config.ladder_len[AS_STABLE] = sizeof(stable) / sizeof(stable[0]);
    p->as_config.ladder_confirm[AS_STABLE] = 3;
    p->as_config.ladders[AS_ACTIVE] = active;
    p->as_config.ladder_len[AS_ACTIVE] = sizeof(active) / sizeof(active[0]);
    p->as_config.ladder_confirm[AS_ACTIVE] = 2;
    p->as_config.ladders[AS_ALERT] = alert;
    p->as_config.ladder_len[AS_ALERT] = sizeof(alert) / sizeof(alert[0]);
    p->as_config.ladder_confirm[AS_ALERT] = 1;
    p->as_config.up_first_sample = true;
    p->as_config.up_on_event = true;
    p->as_config.up_on_state_change = true;
    p->as_config.up_on_interval_change = true;
    p->as_config.heartbeat_s = 60.0f;
    p->as_config.delta_threshold = 2.0f;
    p->fault_interval_s = 20.0f;
    p->degraded_interval_s = 10.0f;
    p->fault_reminder_s = 300.0f;
    p->temperature_threshold = 32.0f;
    p->temperature_margin = 0.0f;
}
#else
#error "Select an explicit B1 timing profile"
#endif
