"""Generate B1's C parameters from validated JSON; no ESP-IDF is needed."""
import argparse
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common.settings import node_settings, SETTINGS

TARGET = Path(__file__).resolve().parents[1] / 'firmware/b1/main/b1_profiles.h'

def number(value):
    return f'{float(value):.9g}' + ('.0f' if float(value).is_integer() else 'f')

def generate():
    lines = ['/* Generated by scripts/generate_b1_profiles.py; edit config JSON. */', '#pragma once']
    for i, profile in enumerate(('deployment', 'lab', 'simulation')):
        lines.append(('#if' if i == 0 else '#elif') + ' defined(CONFIG_B1_' + ('DEPLOYMENT_MODE' if profile == 'deployment' else 'LAB_MODE' if profile == 'lab' else 'SIMULATION_MODE') + ')')
        n = node_settings(profile, physical=True); a = n['adaptive']
        lines += [f'#define B1_PROFILE_NAME "{profile}"', 'static void configure_profile(b1_policy_t *p) {']
        for state in ('stable', 'active', 'alert'):
            lines.append(f'    static const float {state}[] = {{{", ".join(number(v) for v in a["ladders"][state])}}};')
        for field in ('temperature', 'humidity'):
            c = n['trust_channels'][field]
            lines.append(f'    const sensor_trust_config_t {field} = {{' + ', '.join(str(c[k]) if k.endswith('window') or k == 'missing_limit' else number(c[k]) for k in ('min_value','max_value','stuck_epsilon','stuck_window','spike_threshold','drift_window','drift_threshold','missing_limit')) + '};')
            lines.append(f'    sensor_trust_init(&p->{field}, &{field});')
        for idx, (name, c) in enumerate(a['channels'].items()):
            use = str(c['use']).lower()
            lines += [f'    p->cd_config.channels[{idx}] = (cd_channel_cfg_t){{{use}, {number(c["noise_floor"])}}};', f'    p->as_config.delta_channel_use[{idx}] = {use};', f'    p->as_config.delta_noise_floor[{idx}] = {number(c["noise_floor"])};']
        for k,v in a['analyzer'].items(): lines.append(f'    p->cd_config.{k} = {number(v)};')
        lines.append(f'    p->cd_config.min_interval_s = {number(n["sampling"]["min_interval"])};')
        for k in ('event_threshold','event_min_duration_s'):lines.append(f'    p->cd_config.{k} = {number(a[k])};')
        for k,v in n['sampling'].items():lines.append(f'    p->as_config.{k} = {number(v)};')
        for k in ('stable_threshold','active_threshold','hysteresis_fraction'):lines.append(f'    p->as_config.{k} = {number(a[k])};')
        for state in ('stable','active','alert'):
            enum='AS_'+state.upper()
            lines += [f'    p->as_config.ladders[{enum}] = {state};', f'    p->as_config.ladder_len[{enum}] = sizeof({state}) / sizeof({state}[0]);', f'    p->as_config.ladder_confirm[{enum}] = {a["ladder_confirmations"][state]};']
        for k,v in a['upload'].items():
            field = {'upload_first_sample':'up_first_sample','on_event':'up_on_event','on_state_change':'up_on_state_change','on_interval_change':'up_on_interval_change'}.get(k,k)
            lines.append(f'    p->as_config.{field} = {str(v).lower() if isinstance(v,bool) else number(v)};')
        for k in ('fault_interval_s','degraded_interval_s','fault_reminder_s'):lines.append(f'    p->{k} = {number(n[k])};')
        lines.append(f'    p->temperature_threshold = {number(SETTINGS["policy"]["temperature_threshold"])};')
        lines.append(f'    p->temperature_margin = {number(n["control_relevance"]["margins"]["temperature"])};')
        lines.append('}')
    lines += ['#else', '#error "Select an explicit B1 timing profile"', '#endif', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    output=generate()
    if args.check:
        if TARGET.read_text() != output:raise SystemExit('B1 profiles are stale; run scripts/generate_b1_profiles.py')
    else:TARGET.write_text(output)
